apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: always-latest01
  namespace: argocd
  annotations:
    apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: always-latest01
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=ghcr.io/nikitavpatil74/gitops-at-scale
    argocd-image-updater.argoproj.io/example.update-strategy: latest
spec:
  project: default

  source:
    repoURL: https://github.com/nikitavpatil74/GitOps-at-scale
    targetRevision: HEAD
    path: ./image-updater/example-app/envs/qa/
   
  destination:
    server: https://kubernetes.default.svc
    namespace: qa

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
   
